const GEN_NOTE = '<!-- Generated by scripts/validate-scenarios.sh — do not edit by hand. -->';
export const CATALOG_BEGIN = '<!-- BEGIN SCENARIO CATALOG -->';
export const CATALOG_END = '<!-- END SCENARIO CATALOG -->';

const DIFFICULTY_RANK = new Map([
  ['beginner', 0],
  ['intermediate', 1],
  ['advanced', 2],
]);

function difficultyRank(difficulty) {
  return DIFFICULTY_RANK.get(difficulty) ?? Number.MAX_SAFE_INTEGER;
}

function compareLexical(a, b) {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

function sortCatalogScenarios(scenarios) {
  return scenarios.slice().sort((a, b) => {
    const ad = difficultyRank(a.manifest.difficulty);
    const bd = difficultyRank(b.manifest.difficulty);
    if (ad !== bd) return ad - bd;
    const at = a.manifest.title ?? a.id;
    const bt = b.manifest.title ?? b.id;
    const titleDiff = compareLexical(at, bt);
    if (titleDiff !== 0) return titleDiff;
    return compareLexical(a.id, b.id);
  });
}

function renderRow(scenario) {
  const { id, manifest } = scenario;
  const title = manifest.title ?? id;
  const minutes = manifest.estimatedMinutes ? `${manifest.estimatedMinutes}m` : '—';
  const difficulty = manifest.difficulty ?? '—';
  const cost = manifest.costProfile ?? '—';
  return `| [${title}](scenarios/${id}/) | ${manifest.platform} | ${manifest.incidentType} | ${manifest.severity} | ${minutes} | ${difficulty} | ${cost} | ${manifest.summary} |`;
}

function findUniqueMarker(source, marker, label) {
  const first = source.indexOf(marker);
  if (first < 0) throw new Error(`Missing ${label} marker`);
  const second = source.indexOf(marker, first + marker.length);
  if (second >= 0) throw new Error(`Duplicate ${label} marker`);
  return first;
}

function getCatalogBlockBounds(source) {
  const beginIndex = findUniqueMarker(source, CATALOG_BEGIN, 'CATALOG_BEGIN');
  const endIndex = findUniqueMarker(source, CATALOG_END, 'CATALOG_END');
  if (beginIndex > endIndex) {
    throw new Error('CATALOG_BEGIN marker must appear before CATALOG_END marker');
  }
  return {
    beginIndex,
    endIndex,
    endEndIndex: endIndex + CATALOG_END.length,
  };
}

export function extractCatalogBlock(source) {
  const { beginIndex, endEndIndex } = getCatalogBlockBounds(source);
  return source.slice(beginIndex, endEndIndex);
}

export function replaceCatalogBlock(source, block) {
  const { beginIndex, endEndIndex } = getCatalogBlockBounds(source);
  return source.slice(0, beginIndex) + block + source.slice(endEndIndex);
}

export function renderCatalog(scenarios) {
  return [
    CATALOG_BEGIN,
    GEN_NOTE,
    '',
    '| Scenario | Platform | Incident | Severity | Est. | Difficulty | Cost | Summary |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...sortCatalogScenarios(scenarios).map(renderRow),
    '',
    CATALOG_END,
  ].join('\n');
}
